name: GH and Hex.pm Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    uses: TanklesXL/gleam_actions/.github/workflows/release.yaml@main
    secrets:
      HEXPM_USER: ${{ secrets.HEXPM_USER }}
      HEXPM_PASS: ${{ secrets.HEXPM_PASS }}
    with:
      gleam_version: 1.5.1
      erlang_version: 27
      test_erlang: true
      test_node: false
