name: release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.2.1"
          rebar3-version: "3"
      - run: gleam format --check src test
      - run: gleam test --target erlang
      - run: gleam publish -y
        env:
          HEXPM_USER: ${{ secrets.HEX_USERNAME }}
          HEXPM_PASS: ${{ secrets.HEX_PASSWORD }}

      - uses: softprops/action-gh-release@v1
